# Site settings
title: Jérémy Ozog
description: "Blog personnel de Jérémy Ozog, développeur C++, web et mobile."
baseurl: ""
url: "http://www.jeremy-ozog.fr"

# Jekyll settings
highlighter: pygments
noslash: true

# Plugins
gems:
  - jekyll-redirect-from # Doc at https://help.github.com/articles/redirects-on-github-pages
  - jekyll-sitemap       # Doc at https://help.github.com/articles/sitemaps-for-github-pages
