# Site settings
title: Jérémy Ozog
description: "Blog personnel de Jérémy Ozog, développeur C++, web et mobile."
baseurl: ""
url: "http://www.jeremy-ozog.fr"

# Build settings
markdown: kramdown
permalink: pretty

# Other plugins
gems:
  - jekyll-redirect-from # gem install jekyll-redirect-from, doc at https://help.github.com/articles/redirects-on-github-pages
  - jekyll-sitemap       # gem install jekyll-sitemap,       doc at https://help.github.com/articles/sitemaps-for-github-pages
